import { Beneficiario } from './beneficiario';

export const MOCK_BENEFICIARIOS: Beneficiario[] = [
  {
    check: 1,
    codigo_projeto: 'RS0195000',
    projeto: 'PA Piratini',
    lote: 101,
    nome_T1: 'João da Silva',
    situacao_T1: 'assentado',
    nome_T2: 'Maria de Souza',
    situacao_T2: 'irregular',
    data_situacao_T2: '12/04/2015',
    regularizacao: 'Assentamento',
    periodo_regularizacao: '24/11/1986',
    status: 'Deferido',
    cpf_T1: '000.000.000-00',
    numero_processo: ['000044000/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '000',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1/04/2015',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'José da Silva',
    nome_mae: 'Maria Aparecida Silva',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande do Sul',
    municipio: 'Piratini',
    codigo_municipio: '4314606',
    tipo_documento: 'RG',
    numero_documento: '123456789',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '12345678900',
  },
  {
    check: 2,
    codigo_projeto: 'RS0195001',
    projeto: 'PA Piratini',
    lote: 102,
    nome_T1: 'Carlos Henrique Almeida',
    situacao_T1: 'irregular',
    nome_T2: 'Patrícia Lima',
    situacao_T2: 'assentado',
    data_situacao_T2: '03/06/2017',
    regularizacao: 'Inclusão',
    periodo_regularizacao: '12/03/2002',
    status: 'Negado',
    cpf_T1: '111.000.000-00',
    numero_processo: ['000000011/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0001',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1975/09/15',
    estado_civil: 'Solteiro',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Antônio Almeida',
    nome_mae: 'Rosa Almeida',
    nacionalidade: 'Brasileira',
    naturalidade: 'Pelotas',
    municipio: 'Pelotas',
    codigo_municipio: '4314408',
    tipo_documento: 'RG',
    numero_documento: '987654321',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '98765432100',
  },
  {
    check: 3,
    codigo_projeto: 'RS0195002',
    projeto: 'PA Piratini',
    lote: 103,
    nome_T1: 'Ana Clara Barbosa',
    situacao_T1: 'evadido',
    nome_T2: 'Pedro Martins',
    situacao_T2: 'enviado',
    data_situacao_T2: '15/09/2010',
    regularizacao: 'Transferido',
    periodo_regularizacao: '03/05/1998',
    status: 'Em Análise',
    cpf_T1: '000.000.000-25',
    numero_processo: ['000000000/2222'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0002',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1990/11/22',
    estado_civil: 'Solteira',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Carlos Barbosa',
    nome_mae: 'Helena Barbosa',
    nacionalidade: 'Brasileira',
    naturalidade: 'Porto Alegre',
    municipio: 'Porto Alegre',
    codigo_municipio: '4314902',
    tipo_documento: 'RG',
    numero_documento: '112233445',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '11122233344',
  },
  {
    check: 4,
    codigo_projeto: 'RS0195003',
    projeto: 'PA Piratini',
    lote: 104,
    nome_T1: 'Bruna Reis Andrade',
    situacao_T1: 'enviado',
    nome_T2: 'Tiago Carvalho',
    situacao_T2: 'irregular',
    data_situacao_T2: '28/07/2012',
    regularizacao: 'Falecimento',
    periodo_regularizacao: '15/08/2001',
    status: 'Suspenso',
    cpf_T1: '000.000.000-02',
    numero_processo: ['456734532/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0003',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1985/03/12',
    estado_civil: 'Viúva',
    falecido: true,
    data_falecimento: '2020-07-14',
    nome_pai: 'Roberto Andrade',
    nome_mae: 'Luciana Andrade',
    nacionalidade: 'Brasileira',
    naturalidade: 'Bagé',
    municipio: 'Bagé',
    codigo_municipio: '4301602',
    tipo_documento: 'RG',
    numero_documento: '556677889',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '22233344455',
  },
  {
    check: 5,
    codigo_projeto: 'RS0195004',
    projeto: 'PA Piratini',
    lote: 105,
    nome_T1: 'Felipe Augusto Nunes',
    situacao_T1: 'assentado',
    nome_T2: 'Juliana Ramos',
    situacao_T2: 'assentado',
    data_situacao_T2: '04/12/2019',
    regularizacao: 'Desistente',
    periodo_regularizacao: '01/04/2004',
    status: 'Cancelado',
    cpf_T1: '000.000.010-00',
    numero_processo: ['645789456/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0004',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1978/07/01',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Paulo Nunes',
    nome_mae: 'Helena Nunes',
    nacionalidade: 'Brasileira',
    naturalidade: 'Canguçu',
    municipio: 'Canguçu',
    codigo_municipio: '4304507',
    tipo_documento: 'RG',
    numero_documento: '665544332',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '33344455566',
  },
  {
    check: 6,
    codigo_projeto: 'RS0195005',
    projeto: 'PA Piratini',
    lote: 106,
    nome_T1: 'Rafael Silveira Gomes',
    situacao_T1: 'enviado',
    nome_T2: 'Fernanda Costa',
    situacao_T2: 'evadido',
    data_situacao_T2: '10/10/2020',
    regularizacao: 'Assentamento',
    periodo_regularizacao: '18/10/2003',
    status: 'Deferido',
    cpf_T1: '000.000.123-00',
    numero_processo: ['123789456/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0005',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1982/09/25',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Sérgio Gomes',
    nome_mae: 'Cláudia Gomes',
    nacionalidade: 'Brasileira',
    naturalidade: 'Pelotas',
    municipio: 'Pelotas',
    codigo_municipio: '4314408',
    tipo_documento: 'RG',
    numero_documento: '445566778',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '44455566677',
  },
  {
    check: 7,
    codigo_projeto: 'RS0195006',
    projeto: 'PA Piratini',
    lote: 107,
    nome_T1: 'Camila Teixeira Rocha',
    situacao_T1: 'assentado',
    nome_T2: 'Lucas Rocha',
    situacao_T2: 'irregular',
    data_situacao_T2: '20/05/2018',
    regularizacao: 'Transferido',
    periodo_regularizacao: '02/09/2002',
    status: 'Negado',
    cpf_T1: '000.456.000-00',
    numero_processo: ['123456789/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0006',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1995-06-17',
    estado_civil: 'Casada',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Marcelo Rocha',
    nome_mae: 'Patrícia Rocha',
    nacionalidade: 'Brasileira',
    naturalidade: 'São Lourenço do Sul',
    municipio: 'São Lourenço do Sul',
    codigo_municipio: '4320008',
    tipo_documento: 'RG',
    numero_documento: '998877665',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '55566677788',
  },
  {
    check: 8,
    codigo_projeto: 'RS0195007',
    projeto: 'PA Piratini',
    lote: 108,
    nome_T1: 'Letícia Moura Leal',
    situacao_T1: 'irregular',
    nome_T2: 'Bruno Farias',
    situacao_T2: 'assentado',
    data_situacao_T2: '11/01/2022',
    regularizacao: 'Inclusão',
    periodo_regularizacao: '19/01/2010',
    status: 'Em Análise',
    cpf_T1: '000.004.000-00',
    numero_processo: ['222222223/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0007',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1988/08/30',
    estado_civil: 'Solteira',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'João Leal',
    nome_mae: 'Sandra Leal',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande',
    municipio: 'Rio Grande',
    codigo_municipio: '4315602',
    tipo_documento: 'RG',
    numero_documento: '123123123',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '66677788899',
  },
  {
    check: 9,
    codigo_projeto: 'RS0195008',
    projeto: 'PA Piratini',
    lote: 109,
    nome_T1: 'Érica Silva Cunha',
    situacao_T1: 'evadido',
    nome_T2: 'André Souza',
    situacao_T2: 'enviado',
    data_situacao_T2: '08/08/2016',
    regularizacao: 'Falecimento',
    periodo_regularizacao: '30/07/1999',
    status: 'Suspenso',
    cpf_T1: '000.048.000-00',
    numero_processo: ['222222222/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0009',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1970/04/05',
    estado_civil: 'Viúva',
    falecido: true,
    data_falecimento: '2018-09-12',
    nome_pai: 'Carlos Cunha',
    nome_mae: 'Maria Cunha',
    nacionalidade: 'Brasileira',
    naturalidade: 'Santa Maria',
    municipio: 'Santa Maria',
    codigo_municipio: '4316907',
    tipo_documento: 'RG',
    numero_documento: '445533221',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '77788899900',
  },
  {
    check: 10,
    codigo_projeto: 'RS0195009',
    projeto: 'PA Piratini',
    lote: 110,
    nome_T1: 'Hugo Carvalho Neves',
    situacao_T1: 'assentado',
    nome_T2: 'Tatiane Lopes',
    situacao_T2: 'assentado',
    data_situacao_T2: '17/02/2023',
    regularizacao: 'Desistente',
    periodo_regularizacao: '12/12/2008',
    status: 'Cancelado',
    cpf_T1: '800.000.000-00',
    numero_processo: ['111111111/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '00010',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1983/12/01',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Alfredo Neves',
    nome_mae: 'Clara Neves',
    nacionalidade: 'Brasileira',
    naturalidade: 'São Gabriel',
    municipio: 'São Gabriel',
    codigo_municipio: '4318309',
    tipo_documento: 'RG',
    numero_documento: '112200334',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '88899900011',
  },
];
