import { Beneficiario } from './beneficiario';

export const MOCK_BENEFICIARIOS: Beneficiario[] = [
  {
    check: 1,
    codigo_projeto: 'RS0195011',
    projeto: 'PA Piratini',
    lote: 102,
    nome_T1: 'Jorge Henrique Amado',
    situacao_T1: 'evadido',
    nome_T2: 'Maria da Silva Souza',
    situacao_T2: 'assentado',
    data_situacao_T2: '10/11/2002',
    regularizacao: 'Inclusão',
    periodo_regularizacao: '12/10/2003',
    status: 'Negado',
    cpf_T1: '111.000.000-00',
    numero_processo: ['000000011/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '001',
    telefone: '(00) 12345-456',
    email: 'aaa@aa.com',
    data_nascimento: '10/12/1988',
    estado_civil: 'Solteiro',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Antônio Almeida',
    nome_mae: 'Rosa Almeida',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande do Sul',
    municipio: 'Pelotas',
    codigo_municipio: '4314408',
    tipo_documento: 'RG',
    numero_documento: '987654321',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '98765432100',

    data_homologacao_Titular: '1/1/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '10/10/2010',
    data_situacao_Conjuge: '10/10/2010',
    data_homologacao_conjuge: '2011/03/09',
    situacao_conjuge: 'assentado',
    aptoPNRA_conjuge: false,
    tipo_lote: 'Agrícola',
    area_lote: 60,
    numero_lote: '102',
    codigo_SNCR: 'SNCR0002',
    denominacao_Gleba: 'Gleba A',
    denominacao_lote: 'Lote 102',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Pelotas',
    estados: 'RS',
    apto_para_beneficiario: 'não',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2005-06-15'),
        data_separacao: null,
        renda_familiar: 3500,
        nome_dependente: 'Denis de Oliveira Borges',
        tipo_dependente: 'Filho',
        nome: 'João Pedro da Silva',
        data_nascimento: new Date('2010-09-25'),
        data_entrada_na_familia: new Date('2010-09-25'),
        cpf_dependente: '98765432100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2005-06-15'),
        data_separacao: null,
        renda_familiar: 3500,
        nome_dependente: 'João de Oliveira Borges',
        tipo_dependente: 'Filho',
        nome: 'João Pedro da Silva',
        data_nascimento: new Date('2010-09-25'),
        data_entrada_na_familia: new Date('2010-09-25'),
        cpf_dependente: '98765432100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '001',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 2,
    codigo_projeto: 'RS0195001',
    projeto: 'PA Piratini',
    lote: 102,
    nome_T1: 'Carlos Henrique Almeida',
    situacao_T1: 'evadido',
    nome_T2: 'Patrícia Lima',
    situacao_T2: 'assentado',
    data_situacao_T2: '10/10/2001',
    regularizacao: 'Inclusão',
    periodo_regularizacao: '12/10/2002',
    status: 'Negado',
    cpf_T1: '111.000.000-00',
    numero_processo: ['000000011/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0001',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '10/12/1988',
    estado_civil: 'Solteiro',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Antônio Almeida',
    nome_mae: 'Rosa Almeida',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande do Sul',
    municipio: 'Pelotas',
    codigo_municipio: '4314408',
    tipo_documento: 'RG',
    numero_documento: '987654321',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '98765432100',

    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '1/1/1999',
    data_situacao_Conjuge: '1/1/1999',
    data_homologacao_conjuge: '2011/03/09',
    situacao_conjuge: 'assentado',
    aptoPNRA_conjuge: false,
    tipo_lote: 'Agrícola',
    area_lote: 60,
    numero_lote: '102',
    codigo_SNCR: 'SNCR0002',
    denominacao_Gleba: 'Gleba A',
    denominacao_lote: 'Lote 102',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Pelotas',
    estados: 'RS',
    apto_para_beneficiario: 'não',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2005-06-15'),
        data_separacao: null,
        renda_familiar: 3500,
        nome_dependente: 'João Pedro da Silva',
        tipo_dependente: 'Filho',
        nome: 'João Pedro da Silva',
        data_nascimento: new Date('2010-09-25'),
        data_entrada_na_familia: new Date('2010-09-25'),
        cpf_dependente: '98765432100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2005-06-15'),
        data_separacao: null,
        renda_familiar: 3500,
        nome_dependente: 'Antonio Carlos Pedro da Silva',
        tipo_dependente: 'Filho',
        nome: 'Antonio Carlos Pedro da Silva',
        data_nascimento: new Date('2010-09-25'),
        data_entrada_na_familia: new Date('2010-09-25'),
        cpf_dependente: '98765432100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0001',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
      {
        codigo_beneficiario: '0001',
        codigo_tipo_bloqueio: '02',
        descricao_bloqueio: 'Bloqueio por inconsistência cadastral',
        codigo_transacao: 'TRX654321',
        data_bloqueio: '2023-09-05',
        codigo_sub_bloqueio: '02B',
        descricao_sub_bloqueio: 'CPF divergente em registros oficiais',
        codigo_motivo_bloqueio: 'MOT456',
        descricao_motivo_bloqueio: 'Dados inconsistentes na Receita Federal',
        desbloqueio_atendido: 'Sim',
        situacao_analise: 'Concluída',
        data_resultado: '2023-09-20',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 3,
    codigo_projeto: 'RS0195002',
    projeto: 'PA Piratini',
    lote: 103,
    nome_T1: 'Ana Clara Barbosa',
    situacao_T1: 'evadido',
    nome_T2: 'Pedro Martins',
    situacao_T2: 'bloqueado',
    data_situacao_T2: '10/10/2015',
    regularizacao: 'Transferido',
    periodo_regularizacao: '10/10/2005',
    status: 'Em Análise',
    cpf_T1: '000.000.000-25',
    numero_processo: ['000000000/2222'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0002',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '5/5/2015',
    estado_civil: 'Solteira',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Carlos Barbosa',
    nome_mae: 'Helena Barbosa',
    nacionalidade: 'Brasileira',
    naturalidade: 'Porto Alegre',
    municipio: 'Porto Alegre',
    codigo_municipio: '4314902',
    tipo_documento: 'RG',
    numero_documento: '112233445',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '11122233344',

    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '10/10/2015',
    data_situacao_Conjuge: '10/10/2000',
    data_homologacao_conjuge: '10/10/2010',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2010-03-20'),
        data_separacao: null,
        renda_familiar: 4200,
        nome_dependente: 'Patrícia Lima',
        tipo_dependente: 'Conjuge',
        nome: 'Patrícia Lima',
        data_nascimento: new Date('1988-01-15'),
        data_entrada_na_familia: new Date('2010-03-20'),
        cpf_dependente: '45678912345',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0002',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 4,
    codigo_projeto: 'RS0195015',
    projeto: 'PA Piratini',
    lote: 102,
    nome_T1: 'Jorge Henrique Amado',
    situacao_T1: 'evadido',
    nome_T2: 'José da Silva Souza',
    situacao_T2: 'assentado',
    data_situacao_T2: '10/11/2002',
    regularizacao: 'Inclusão',
    periodo_regularizacao: '12/10/2003',
    status: 'Negado',
    cpf_T1: '111.000.000-00',
    numero_processo: ['000000011/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0004',
    telefone: '(00) 12345-456',
    email: 'aaa@aa.com',
    data_nascimento: '10/12/1988',
    estado_civil: 'Solteiro',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Antônio Almeida',
    nome_mae: 'Rosa Almeida',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande do Sul',
    municipio: 'Pelotas',
    codigo_municipio: '4314408',
    tipo_documento: 'RG',
    numero_documento: '987654321',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '98765432100',

    data_homologacao_Titular: '1/1/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '10/10/2010',
    data_situacao_Conjuge: '10/10/2010',
    data_homologacao_conjuge: '2011/03/09',
    situacao_conjuge: 'assentado',
    aptoPNRA_conjuge: false,
    tipo_lote: 'Agrícola',
    area_lote: 60,
    numero_lote: '102',
    codigo_SNCR: 'SNCR0002',
    denominacao_Gleba: 'Gleba A',
    denominacao_lote: 'Lote 102',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Pelotas',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2008-07-05'),
        data_separacao: null,
        renda_familiar: 3100,
        nome_dependente: 'Pedro Martins',
        tipo_dependente: 'Conjuge',
        nome: 'Pedro Martins',
        data_nascimento: new Date('1982-04-12'),
        data_entrada_na_familia: new Date('2008-07-05'),
        cpf_dependente: '32165498700',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0003',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
      {
        codigo_beneficiario: '0003',
        codigo_tipo_bloqueio: '02',
        descricao_bloqueio: 'Bloqueio por inconsistência cadastral',
        codigo_transacao: 'TRX654321',
        data_bloqueio: '2023-09-05',
        codigo_sub_bloqueio: '02B',
        descricao_sub_bloqueio: 'CPF divergente em registros oficiais',
        codigo_motivo_bloqueio: 'MOT456',
        descricao_motivo_bloqueio: 'Dados inconsistentes na Receita Federal',
        desbloqueio_atendido: 'Sim',
        situacao_analise: 'Concluída',
        data_resultado: '2023-09-20',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 5,
    codigo_projeto: 'RS0195004',
    projeto: 'PA Piratini',
    lote: 105,
    nome_T1: 'Felipe Augusto Nunes',
    situacao_T1: 'assentado',
    nome_T2: 'Juliana Ramos',
    situacao_T2: 'assentado',
    data_situacao_T2: '04/12/2019',
    regularizacao: 'Desistente',
    periodo_regularizacao: '01/04/2004',
    status: 'Cancelado',
    cpf_T1: '000.000.010-00',
    numero_processo: ['645789456/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0004',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '11/11/1990',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Paulo Nunes',
    nome_mae: 'Helena Nunes',
    nacionalidade: 'Brasileira',
    naturalidade: 'Canguçu',
    municipio: 'Canguçu',
    codigo_municipio: '4304507',
    tipo_documento: 'RG',
    numero_documento: '665544332',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '33344455566',
    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '11/11/1990',
    data_situacao_Conjuge: '11/11/1990',
    data_homologacao_conjuge: '11/11/1990',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2008-07-05'),
        data_separacao: null,
        renda_familiar: 3100,
        nome_dependente: 'Lucas Barbosa',
        tipo_dependente: 'Filho',
        nome: 'Lucas Barbosa',
        data_nascimento: new Date('2012-03-11'),
        data_entrada_na_familia: new Date('2012-03-11'),
        cpf_dependente: '65498732100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0004',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
      {
        codigo_beneficiario: '0004',
        codigo_tipo_bloqueio: '02',
        descricao_bloqueio: 'Bloqueio por inconsistência cadastral',
        codigo_transacao: 'TRX654321',
        data_bloqueio: '2023-09-05',
        codigo_sub_bloqueio: '02B',
        descricao_sub_bloqueio: 'CPF divergente em registros oficiais',
        codigo_motivo_bloqueio: 'MOT456',
        descricao_motivo_bloqueio: 'Dados inconsistentes na Receita Federal',
        desbloqueio_atendido: 'Sim',
        situacao_analise: 'Concluída',
        data_resultado: '2023-09-20',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 6,
    codigo_projeto: 'RS0195005',
    projeto: 'PA Piratini',
    lote: 106,
    nome_T1: 'Rafael Silveira Gomes',
    situacao_T1: 'evadido',
    nome_T2: 'Fernanda Costa',
    situacao_T2: 'evadido',
    data_situacao_T2: '10/10/2020',
    regularizacao: 'Assentamento',
    periodo_regularizacao: '18/10/2003',
    status: 'Deferido',
    cpf_T1: '000.000.123-00',
    numero_processo: ['123789456/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0005',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '11/10/1980',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Sérgio Gomes',
    nome_mae: 'Cláudia Gomes',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande do Sul',
    municipio: 'Pelotas',
    codigo_municipio: '4314408',
    tipo_documento: 'RG',
    numero_documento: '445566778',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '44455566677',
    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '11/10/1981',
    data_situacao_Conjuge: '12/10/1983',
    data_homologacao_conjuge: '10/10/1987',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Solteiro',
        data_uniao: new Date('2020-01-01'),
        data_separacao: null,
        renda_familiar: 2800,
        nome_dependente: 'Fernanda Oliveira',
        tipo_dependente: 'Filha',
        nome: 'Fernanda Oliveira',
        data_nascimento: new Date('2002-07-15'),
        data_entrada_na_familia: new Date('2002-07-15'),
        cpf_dependente: '11223344556',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0005',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 7,
    codigo_projeto: 'RS0195006',
    projeto: 'PA Piratini',
    lote: 107,
    nome_T1: 'Camila Teixeira Rocha',
    situacao_T1: 'assentado',
    nome_T2: 'Lucas Rocha',
    situacao_T2: 'irregular',
    data_situacao_T2: '20/05/2018',
    regularizacao: 'Transferido',
    periodo_regularizacao: '02/09/2002',
    status: 'Negado',
    cpf_T1: '000.456.000-00',
    numero_processo: ['123456789/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0006',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '1995/06/17',
    estado_civil: 'Casada',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Marcelo Rocha',
    nome_mae: 'Patrícia Rocha',
    nacionalidade: 'Brasileira',
    naturalidade: 'São Lourenço do Sul',
    municipio: 'São Lourenço do Sul',
    codigo_municipio: '4320008',
    tipo_documento: 'RG',
    numero_documento: '998877665',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '55566677788',
    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '02/09/2002',
    data_situacao_Conjuge: '02/08/2003',
    data_homologacao_conjuge: '02/09/2002',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2003-09-10'),
        data_separacao: null,
        renda_familiar: 5000,
        nome_dependente: 'Carlos Mendes',
        tipo_dependente: 'Conjuge',
        nome: 'Carlos Mendes',
        data_nascimento: new Date('1978-11-22'),
        data_entrada_na_familia: new Date('2003-09-10'),
        cpf_dependente: '22334455667',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0006',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 8,
    codigo_projeto: 'RS0195007',
    projeto: 'PA Piratini',
    lote: 108,
    nome_T1: 'Letícia Moura Leal',
    situacao_T1: 'irregular',
    nome_T2: 'Bruno Farias',
    situacao_T2: 'assentado',
    data_situacao_T2: '11/01/2022',
    regularizacao: 'Inclusão',
    periodo_regularizacao: '19/01/2010',
    status: 'Em Análise',
    cpf_T1: '000.004.000-00',
    numero_processo: ['222222223/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0007',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '02/09/2002',
    estado_civil: 'Solteira',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'João Leal',
    nome_mae: 'Sandra Leal',
    nacionalidade: 'Brasileira',
    naturalidade: 'Rio Grande',
    municipio: 'Rio Grande',
    codigo_municipio: '4315602',
    tipo_documento: 'RG',
    numero_documento: '123123123',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '66677788899',
    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '02/09/2008',
    data_situacao_Conjuge: '08/09/2010',
    data_homologacao_conjuge: '08/09/2011',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2015-05-18'),
        data_separacao: null,
        renda_familiar: 3600,
        nome_dependente: 'Juliana Rocha',
        tipo_dependente: 'Conjuge',
        nome: 'Juliana Rocha',
        data_nascimento: new Date('1990-02-14'),
        data_entrada_na_familia: new Date('2015-05-18'),
        cpf_dependente: '33445566778',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0007',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
      {
        codigo_beneficiario: '0007',
        codigo_tipo_bloqueio: '02',
        descricao_bloqueio: 'Bloqueio por inconsistência cadastral',
        codigo_transacao: 'TRX654321',
        data_bloqueio: '2023-09-05',
        codigo_sub_bloqueio: '02B',
        descricao_sub_bloqueio: 'CPF divergente em registros oficiais',
        codigo_motivo_bloqueio: 'MOT456',
        descricao_motivo_bloqueio: 'Dados inconsistentes na Receita Federal',
        desbloqueio_atendido: 'Sim',
        situacao_analise: 'Concluída',
        data_resultado: '2023-09-20',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 9,
    codigo_projeto: 'RS0195008',
    projeto: 'PA Piratini',
    lote: 109,
    nome_T1: 'Érica Silva Cunha',
    situacao_T1: 'evadido',
    nome_T2: 'André Souza',
    situacao_T2: 'enviado',
    data_situacao_T2: '08/08/2016',
    regularizacao: 'Falecimento',
    periodo_regularizacao: '30/07/1999',
    status: 'Suspenso',
    cpf_T1: '000.048.000-00',
    numero_processo: ['222222222/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '0009',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '08/09/2010',
    estado_civil: 'Viúva',
    falecido: true,
    data_falecimento: '08/09/2015',
    nome_pai: 'Carlos Cunha',
    nome_mae: 'Maria Cunha',
    nacionalidade: 'Brasileira',
    naturalidade: 'Santa Maria',
    municipio: 'Santa Maria',
    codigo_municipio: '4316907',
    tipo_documento: 'RG',
    numero_documento: '445533221',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '77788899900',
    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '01/01/2012',
    data_situacao_Conjuge: '01/01/2013',
    data_homologacao_conjuge: '02/03/2014',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2015-05-18'),
        data_separacao: null,
        renda_familiar: 3600,
        nome_dependente: 'Felipe Rocha',
        tipo_dependente: 'Filho',
        nome: 'Felipe Rocha',
        data_nascimento: new Date('2018-09-09'),
        data_entrada_na_familia: new Date('2018-09-09'),
        cpf_dependente: '99887766554',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '0009',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
      {
        codigo_beneficiario: '0009',
        codigo_tipo_bloqueio: '02',
        descricao_bloqueio: 'Bloqueio por inconsistência cadastral',
        codigo_transacao: 'TRX654321',
        data_bloqueio: '2023-09-05',
        codigo_sub_bloqueio: '02B',
        descricao_sub_bloqueio: 'CPF divergente em registros oficiais',
        codigo_motivo_bloqueio: 'MOT456',
        descricao_motivo_bloqueio: 'Dados inconsistentes na Receita Federal',
        desbloqueio_atendido: 'Sim',
        situacao_analise: 'Concluída',
        data_resultado: '2023-09-20',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
  {
    check: 10,
    codigo_projeto: 'RS0195009',
    projeto: 'PA Piratini',
    lote: 110,
    nome_T1: 'Hugo Carvalho Neves',
    situacao_T1: 'assentado',
    nome_T2: 'Tatiane Lopes',
    situacao_T2: 'assentado',
    data_situacao_T2: '17/02/2023',
    regularizacao: 'Desistente',
    periodo_regularizacao: '12/12/2008',
    status: 'Cancelado',
    cpf_T1: '800.000.000-00',
    numero_processo: ['111111111/0000'],
    acoes: [
      'Detalhar',
      'Alteração Cadastral',
      'Histórico de Operações',
      'Histórico do Beneficiario',
      'Espelho do Beneficiário',
      'Inclusão/Alteração de Cônjuge',
      'Bloqueio / Desbloqueio',
      'Sucessão do Lote',
    ],
    codigo_beneficiario: '00010',
    telefone: '(00) 00000-0000',
    email: 'aaa@aa.com',
    data_nascimento: '02/01/2014',
    estado_civil: 'Casado',
    falecido: false,
    data_falecimento: null,
    nome_pai: 'Alfredo Neves',
    nome_mae: 'Clara Neves',
    nacionalidade: 'Brasileira',
    naturalidade: 'São Gabriel',
    municipio: 'São Gabriel',
    codigo_municipio: '4318309',
    tipo_documento: 'RG',
    numero_documento: '112200334',
    orgao_emissor: 'SSP',
    uf_orgao: 'RS',
    numero_nis: '88899900011',
    data_homologacao_Titular: '12/12/2020',
    situacao_Titular: 'evadido',
    data_situacao_Titular: '02/03/2014',
    data_situacao_Conjuge: '02/03/2025',
    data_homologacao_conjuge: '02/03/2020',
    situacao_conjuge: 'bloqueado',
    aptoPNRA_conjuge: true,
    tipo_lote: 'Agrícola',
    area_lote: 45,
    numero_lote: '103',
    codigo_SNCR: 'SNCR0003',
    denominacao_Gleba: 'Gleba B',
    denominacao_lote: 'Lote 103',
    observacao:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pharetra lectus eget lacinia convallis. Aliquam blandit odio arcu. Vestibulum eget neque orci.',
    data_observacao: '10/10/2010',
    municipios: 'Porto Alegre',
    estados: 'RS',
    apto_para_beneficiario: 'sim',
    dependentes: [
      {
        situacao_conjugal: 'Viúvo',
        data_uniao: new Date('1995-12-01'),
        data_separacao: new Date('2010-08-20'),
        renda_familiar: 2500,
        nome_dependente: 'Ana Beatriz Costa',
        tipo_dependente: 'Filha',
        nome: 'Ana Beatriz Costa',
        data_nascimento: new Date('1996-03-05'),
        data_entrada_na_familia: new Date('1996-03-05'),
        cpf_dependente: '44556677889',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
    bloqueios: [
      {
        codigo_beneficiario: '00010',
        codigo_tipo_bloqueio: '01',
        descricao_bloqueio: 'Bloqueio por pendência documental',
        codigo_transacao: 'TRX987654',
        data_bloqueio: '2023-07-15',
        codigo_sub_bloqueio: '01A',
        descricao_sub_bloqueio: 'Ausência de comprovante de residência',
        codigo_motivo_bloqueio: 'MOT123',
        descricao_motivo_bloqueio:
          'Falta de documentação exigida para análise cadastral',
        desbloqueio_atendido: 'Não',
        situacao_analise: 'Em análise',
        data_resultado: '2023-08-10',
      },
    ],
    tela_lote: [
      {
        tipo_lote: 'Assentamento',
        area_lote: 25.5,
        numero_lote: 'L123',
        codigo_SNCR: 'SNCR2023001',
        denominacao_Gleba: 'Gleba Santa Maria',
        denominacao_lote: 'Lote 45 - Santa Maria',
      },
      {
        tipo_lote: 'Reforma Agrária',
        area_lote: 32.75,
        numero_lote: 'L456',
        codigo_SNCR: 'SNCR2023002',
        denominacao_Gleba: 'Gleba Boa Esperança',
        denominacao_lote: 'Lote 12 - Boa Esperança',
      },
    ],
  },
];
