/*import { UnidadeFamiliar } from '../../lista/unidadeFamiliar';
export const MOCK_DEPENDENTES: {
  codigo_beneficiario: string;
  dependentes: UnidadeFamiliar[];
}[] = [
  {
    codigo_beneficiario: '000',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2005-06-15'),
        renda_familiar: 3500,
        nome_dependente: 'Maria de Souza',
        tipo_dependente: 'Conjuge',
        nome: 'Maria de Souza',
        data_nascimento: new Date('1985-08-10'),
        data_entrada_na_familia: new Date('2005-06-15'),
        cpf_dependente: '12345678901',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2005-06-15'),
        renda_familiar: 3500,
        nome_dependente: 'João Pedro da Silva',
        tipo_dependente: 'Filho',
        nome: 'João Pedro da Silva',
        data_nascimento: new Date('2010-09-25'),
        data_entrada_na_familia: new Date('2010-09-25'),
        cpf_dependente: '98765432100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0001',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2010-03-20'),
        renda_familiar: 4200,
        nome_dependente: 'Patrícia Lima',
        tipo_dependente: 'Conjuge',
        nome: 'Patrícia Lima',
        data_nascimento: new Date('1988-01-15'),
        data_entrada_na_familia: new Date('2010-03-20'),
        cpf_dependente: '45678912345',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0002',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2008-07-05'),
        renda_familiar: 3100,
        nome_dependente: 'Pedro Martins',
        tipo_dependente: 'Conjuge',
        nome: 'Pedro Martins',
        data_nascimento: new Date('1982-04-12'),
        data_entrada_na_familia: new Date('2008-07-05'),
        cpf_dependente: '32165498700',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2008-07-05'),
        renda_familiar: 3100,
        nome_dependente: 'Lucas Barbosa',
        tipo_dependente: 'Filho',
        nome: 'Lucas Barbosa',
        data_nascimento: new Date('2012-03-11'),
        data_entrada_na_familia: new Date('2012-03-11'),
        cpf_dependente: '65498732100',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  // ... continuar para os outros beneficiários
  {
    codigo_beneficiario: '0003',
    dependentes: [
      {
        situacao_conjugal: 'Solteiro',
        data_uniao: new Date('2020-01-01'),
        renda_familiar: 2800,
        nome_dependente: 'Fernanda Oliveira',
        tipo_dependente: 'Filha',
        nome: 'Fernanda Oliveira',
        data_nascimento: new Date('2002-07-15'),
        data_entrada_na_familia: new Date('2002-07-15'),
        cpf_dependente: '11223344556',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0004',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2003-09-10'),
        renda_familiar: 5000,
        nome_dependente: 'Carlos Mendes',
        tipo_dependente: 'Conjuge',
        nome: 'Carlos Mendes',
        data_nascimento: new Date('1978-11-22'),
        data_entrada_na_familia: new Date('2003-09-10'),
        cpf_dependente: '22334455667',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0005',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2015-05-18'),
        renda_familiar: 3600,
        nome_dependente: 'Juliana Rocha',
        tipo_dependente: 'Conjuge',
        nome: 'Juliana Rocha',
        data_nascimento: new Date('1990-02-14'),
        data_entrada_na_familia: new Date('2015-05-18'),
        cpf_dependente: '33445566778',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2015-05-18'),
        renda_familiar: 3600,
        nome_dependente: 'Felipe Rocha',
        tipo_dependente: 'Filho',
        nome: 'Felipe Rocha',
        data_nascimento: new Date('2018-09-09'),
        data_entrada_na_familia: new Date('2018-09-09'),
        cpf_dependente: '99887766554',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0006',
    dependentes: [
      {
        situacao_conjugal: 'Viúvo',
        data_uniao: new Date('1995-12-01'),
        data_separacao: new Date('2010-08-20'),
        renda_familiar: 2500,
        nome_dependente: 'Ana Beatriz Costa',
        tipo_dependente: 'Filha',
        nome: 'Ana Beatriz Costa',
        data_nascimento: new Date('1996-03-05'),
        data_entrada_na_familia: new Date('1996-03-05'),
        cpf_dependente: '44556677889',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0007',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2007-04-04'),
        renda_familiar: 4000,
        nome_dependente: 'Ricardo Alves',
        tipo_dependente: 'Conjuge',
        nome: 'Ricardo Alves',
        data_nascimento: new Date('1983-06-12'),
        data_entrada_na_familia: new Date('2007-04-04'),
        cpf_dependente: '55667788990',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0008',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2001-02-17'),
        renda_familiar: 4700,
        nome_dependente: 'Simone Farias',
        tipo_dependente: 'Conjuge',
        nome: 'Simone Farias',
        data_nascimento: new Date('1979-10-30'),
        data_entrada_na_familia: new Date('2001-02-17'),
        cpf_dependente: '66778899001',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2001-02-17'),
        renda_familiar: 4700,
        nome_dependente: 'André Farias',
        tipo_dependente: 'Filho',
        nome: 'André Farias',
        data_nascimento: new Date('2005-08-21'),
        data_entrada_na_familia: new Date('2005-08-21'),
        cpf_dependente: '77665544332',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '0009',
    dependentes: [
      {
        situacao_conjugal: 'Casado',
        data_uniao: new Date('2012-11-11'),
        renda_familiar: 3300,
        nome_dependente: 'Tatiane Lopes',
        tipo_dependente: 'Conjuge',
        nome: 'Tatiane Lopes',
        data_nascimento: new Date('1991-07-19'),
        data_entrada_na_familia: new Date('2012-11-11'),
        cpf_dependente: '88990011223',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
  {
    codigo_beneficiario: '00010',
    dependentes: [
      {
        situacao_conjugal: 'Solteiro',
        data_uniao: new Date('2019-05-25'),
        renda_familiar: 2950,
        nome_dependente: 'Roberto Silva',
        tipo_dependente: 'Filho',
        nome: 'Roberto Silva',
        data_nascimento: new Date('2000-12-12'),
        data_entrada_na_familia: new Date('2000-12-12'),
        cpf_dependente: '99001122334',
        associacao_unidade_familiar: 'Associação Rural Piratini',
      },
    ],
  },
];
*/
